
export const GET_MOVIES_REQUEST = "GET_MOVIES_REQUEST";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAILURE = "GET_MOVIES_FAILURE";

export const GET_MOVIE_DETAIL_REQUEST = "GET_MOVIE_DETAIL_REQUEST";
export const GET_MOVIE_DETAIL_SUCCESS = "GET_MOVIE_DETAIL_SUCCESS";
export const GET_MOVIE_DETAIL_FAILURE = "GET_MOVIE_DETAIL_FAILURE";

export const GET_PLANET_REQUEST = "GET_PLANET_REQUEST";
export const GET_PLANET_SUCCESS = "GET_PLANET_SUCCESS";
export const GET_PLANET_FAILURE = "GET_PLANET_FAILURE";

export const GET_PLANET_DETAIL_REQUEST = "GET_PLANET_DETAIL_REQUEST";
export const GET_PLANET_DETAIL_SUCCESS = "GET_PLANET_DETAIL_SUCCESS";
export const GET_PLANET_DETAIL_FAILURE = "GET_PLANET_DETAIL_FAILURE";

export const GET_PEOPLE_REQUEST = "GET_PEOPLE_REQUEST";
export const GET_PEOPLE_SUCCESS = "GET_PEOPLE_SUCCESS";
export const GET_PEOPLE_FAILURE = "GET_PEOPLE_FAILURE";

export const GET_PEOPLE_DETAIL_REQUEST = "GET_PEOPLE_DETAIL_REQUEST";
export const GET_PEOPLE_DETAIL_SUCCESS = "GET_PEOPLE_DETAIL_SUCCESS";
export const GET_PEOPLE_DETAIL_FAILURE = "GET_PEOPLE_DETAIL_FAILURE";

